### ISSUE TITLE
filterFn called in reverse order / filterFn on nodes called after their entries in reverse mode

### ISSUE THREAD

**Issue by jclaveau** [blackflux/object-scan#1675] opened 2022-03-09 13:02 UTC
```typescript
const testTree = [
  {
    name: 'node_1',
  },
  {
    name: 'node_2',
    children: [
      {
        name: 'node_2_1',
        name2: 'node_2_1',
        name3: 'node_2_1',
      },
      {
        name: 'node_2_2',
        name2: 'node_2_2',
        name3: 'node_2_2',
      },
    ]
  },
];

const out = objectScan(['**'], {
  filterFn: (function({ key, property, value, parent }: ObjectScan.ScannedItem) {
    console.log(key.join(', '), property, value);
  })
})(
  testTree
);

console.log('out', out)
```

=> 
![image](https://user-images.githubusercontent.com/1556489/157446374-ba065395-532d-4521-8632-49453a803289.png)

I don't know if it is expected but is seems counter intuitive to me. Espacially after having read `Invoked in same order as matches would appear in result.` and `This method is conceptually similar to Array.filter()` in https://github.com/blackflux/object-scan#filterfn

Especially if, like in my case, you want to map a tree to construct another one in the same order.

**Comment by jclaveau** [comment] 2022-03-09 13:11
After reading about `reverse` option, I now get why this behaviour (safe delete). I think it should be overlined in the `filterFn` doc.

**Comment by jclaveau** [comment] 2022-03-09 13:31
I don't know if another issue would be a better place for it but, in `reverse` mode, properties are scanned before their parent.
In my case it makes your lib unusable for my purpose: mapping a tree to build a new one with the same hierarchy. 

![image](https://user-images.githubusercontent.com/1556489/157451295-31f59e37-fa13-438d-acc2-f2a4ed339879.png)

**Comment by simlu** [comment] 2022-03-09 13:35
This library was originally written for a very specific use case (take a look at [object-rewrite](https://github.com/blackflux/object-rewrite) if you want to know more). Safe delete and performance were two core requirement. 

As this library evolved, more and more options were added - reverse being one of several that deal with traversal order. The traversal order is actually pretty complex and there is a [ticket](https://github.com/blackflux/object-scan/issues/1654) to improve the documentation on it. Performance is still a design goal.

So to summarize the reasons: reverse true is the default, because it was the original default before the option existed, safe delete was required and because it is more performant.

This library is made for speed and there are extensive automatic tests to find any regression. In a lot of cases the traversal order doesn't matter, but speed does. Unfortunately using reverse true comes with a small [performance penalty](https://github.com/blackflux/object-scan/blob/9ed4e155679aa7b42f0d1d010ca18b79508733e0/src/core/find.js#L160) at least for now.

Thank you for writing this ticket and I will consider adding a note to the filterFn doc in the future (I've added a note to the mentioned issue)

**Comment by simlu** [comment] 2022-03-09 13:37
As to your last comment, "leaf-up" traversal is also a requirement and by design. This is all documented I think.

You could use the breakFn if you wanted to traverse parents before their children. That works reasonably well for the use cases where we needed this behaviour

**Comment by simlu** [comment] 2022-03-09 13:40
This might help you https://github.com/blackflux/object-lib/blob/master/src/core/clone.js

**Comment by simlu** [comment] 2022-06-19 05:22
Will need to improve the readme with a traversal order section. There is a separate ticket (as linked). So I'm closing this one

**Closed by simlu** 2022-06-19 05:22 UTC
